In [3]:
import pandas as pd
import numpy as np
import seaborn as sns

In [14]:
iris = sns.load_dataset('iris')
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [15]:
iris = iris.drop(labels = 'species', axis = 1)
iris.head()

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [16]:
iris['sepal_sum'] = iris['sepal_length'] + iris['sepal_width']
iris.head()

   sepal_length  sepal_width  petal_length  petal_width  sepal_sum
0           5.1          3.5           1.4          0.2        8.6
1           4.9          3.0           1.4          0.2        7.9
2           4.7          3.2           1.3          0.2        7.9
3           4.6          3.1           1.5          0.2        7.7
4           5.0          3.6           1.4          0.2        8.6

In [19]:
mean = [np.mean(iris['sepal_length']), 
        np.mean(iris['sepal_width']),
        np.mean(iris['sepal_sum']),
        np.mean(iris['petal_length']),
        np.mean(iris['petal_width'])]

summary_dict = {'mean':mean}

summary_df = pd.DataFrame(data = summary_dict)

summary_df

       mean
0  5.843333
1  3.057333
2  8.900667
3  3.758000
4  1.199333

In [21]:
std = list(iris.std())

summary_dict = {'std' :std}

summary_df = pd.DataFrame(data = summary_dict)

summary_df

        std
0  0.828066
1  0.435866
2  1.765298
3  0.762238
4  0.889272

In [22]:
min = list(iris.min())

summary_dict = {'min' :min}

summary_df = pd.DataFrame(data = summary_dict)

summary_df

   min
0  4.3
1  2.0
2  1.0
3  0.1
4  6.8

In [23]:
max = list(iris.max())

summary_dict = {'max' :max}

summary_df = pd.DataFrame(data = summary_dict)

summary_df

    max
0   7.9
1   4.4
2   6.9
3   2.5
4  11.7